/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'chaospie' at '08/02/16 18:30' with Gradle 2.11
 *
 * @author chaospie, @date 08/02/16 18:30
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
